services:
    postgres:
        image: 'postgres:16.4-alpine'
        working_dir: /application
        volumes:
            - './db/:/application'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=xinforinpola
        ports:
            - '55432:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './www/:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - './www/:/application'
            - './docker/php-fpm/supervisor.conf:/etc/supervisor/conf.d/queue.conf'